import 'package:app_demo/models/information_animal.dart';
import 'package:app_demo/ui/animais_terrestres.dart';
import 'package:flutter/material.dart';

Map<String, dynamic> jsonTest = {
  "animais": [
    {
      "classificacao_animal":"Classificação: Terrestre",
      "nome_animal": "Leao",
      "bioma_animal": "Bioma: Savana",
      "familia_cientifica_animal": "Famlia.Cientí: Felidae",
      "populacao_animal": "População: 20.000",
      "peso_animal": "Peso: 190kg",
      "sexo_animal": "Sexo: M",
      "altura_animal": "Altura: De 1,37 a 2m",
      "tipo_animal": "Tipo do Animal: Mamífero",
      "alimentacao_animal": "Carnívoro",
      "nome_cientifico_animal": 'Nome Cientí: Pantera Leo',
      'image_animal': 'lib/images/leao.jpg',
      'image_primeira_animal': 'lib/images/leaoarvore.jpg' ,
      'image_segunda_animal': 'lib/images/leaoarv.jpg',
      'image_terceira_animal': 'lib/images/leaoalbino.jpg',
    },
    //Inserindo o animal Leão

    {
      "classificacao_animal":"Classificação: Venenoso",
      "nome_animal": "Capivara",
      "bioma_animal": "Bioma: Semi-aquático",
      "familia_cientifica_animal": "Fami.Cienti: Hydrochoerus hydrochaeris",
      "populacao_animal": "População: Desconhecida",
      "peso_animal": "Peso: De 36 a 66kg",
      "sexo_animal": "Sexo: M",
      "altura_animal": "Altura: De 54 á  64cm",
      "tipo_animal": "Tipo Animal: Mamífero roedor",
      "alimentacao_animal": "Herbívoro",
      "nome_cientifico_animal": 'Nome Cientifico: Caviidae',
      'image_animal': 'lib/images/capivara.png',
      'image_primeira_animal': 'lib/images/capivaraprimeira.png',
      'image_segunda_animal': 'lib/images/capivarasegundas.jpg',
      'image_terceira_animal': 'lib/images/capivaraterceiras.jpg'
    },
    //Inserindo o animal Capivara
    {
      "classificacao_animal":"Classificação: Venenoso",
      "nome_animal": "Dragão de Komodo",
      "bioma_animal": "Bioma: Savana",
      "familia_cientifica_animal": " Familia.Cienti: Varanus komodoensis",
      "populacao_animal": "População: 1.830",
      "peso_animal": " Peso: 160kg",
      "sexo_animal": "Sexo: M",
      "altura_animal": "Altura: 40cm de Altura",
      "tipo_animal": "Tipo Animal: Reptil",
      "alimentacao_animal": "Carnívoro",
      "nome_cientifico_animal": 'Nome Cientifico: Varanus',
      'image_animal': 'lib/images/komodo.jpg',
      'image_primeira_animal': 'lib/images/komododragao.png',
      'image_segunda_animal': 'lib/images/komodosegundo.jpg',
      'image_terceira_animal': 'lib/images/komodoterceiro.png'
    },
    //Inserindo o animal Dragão de Komodo

     {
      "classificacao_animal":"Classificação: Terrestre",
      "nome_animal": "Gorila",
      "bioma_animal": "Bioma: Temperado e tropical",
      "familia_cientifica_animal": " Familia.Cienti: Gorila",
      "populacao_animal": "População: Aprox. 1.000",
      "peso_animal": "Peso: 200kg",
      "sexo_animal": "Sexo: M",
      "altura_animal": "Altura: De 35 a 60cm", 
      "tipo_animal": "Tipo Animal: Mamífero",
      "alimentacao_animal": "Herbívoro",
      "nome_cientifico_animal": 'Nome Cientifico: Hominidae',
      'image_animal': 'lib/images/gorila.jpg',
      'image_primeira_animal': 'lib/images/gorilaprimeiro.jpg',
      'image_segunda_animal': 'lib/images/gorilasegundo.png',
      'image_terceira_animal': 'lib/images/gorilaterceiros.jpg'
    },
    //Inserindp o animal Gorila
    
     {
      "classificacao_animal":"Classificação: Aquático",
      "nome_animal": "Tubarão branco",
      "bioma_animal": "Bioma: Temperado e tropical",
      "familia_cientifica_animal": " Familia.Cienti: Lamnidae",
      "populacao_animal": "População:  Aprox. 3.500",
      "peso_animal": "Peso: De 520 a 1.100kg",
      "sexo_animal": "Sexo: M",
      "altura_animal": "Tamanho: De 4 a 6m de comprimento",
      "tipo_animal": "Tipo Animal: Mamífero",
      "alimentacao_animal": "Carnívoro",
      "nome_cientifico_animal": 'Nome Cientifico: Carcharias',
      'image_animal': 'lib/images/tubarao.jpg',
      'image_primeira_animal': 'lib/images/tubaraofera.jpg',
      'image_segunda_animal': 'lib/images/tubaraosalto.jpg',
      'image_terceira_animal': 'lib/images/tub.jpg'
    },
    //Inserindo o animal Tubarão branco

     {
      "classificacao_animal":"Classificação: Aquático",
      "nome_animal": "Ornitorrinco",
      "bioma_animal": "Bioma: Ambiente aquático",
      "familia_cientifica_animal": " Familia.Cienti: Anatinus",
      "populacao_animal": "População: 200 mil",
      "peso_animal": "Peso: 2,4kg",
      "sexo_animal": "Sexo: M",
      "altura_animal": "Tamanho: 50cm de comprimento",
      "tipo_animal": "Tipo Animal: Mamífero",
      "alimentacao_animal": "Carnívoro",
      "nome_cientifico_animal": 'Nome Cientifico: Ornithorhynchidae',
      'image_animal': 'lib/images/ornitorrinco.png',
      'image_primeira_animal': 'lib/images/ornitorrinco.jpg',
      'image_segunda_animal': 'lib/images/ornisegundo.jpg',
      'image_terceira_animal': 'lib/images/orni.jpg',
    },
    //Inserindo o animal Ornitorrinco

     {
      "classificacao_animal":"Classificação: Aquático",
      "nome_animal": "Urso polar",
      "bioma_animal": "Bioma: Circulo polar ártico",
      "familia_cientifica_animal": " Familia.Cienti: Ursidae",
      "populacao_animal": "População: Em cerca de 25.000",
      "peso_animal": "Peso: 450kg",
      "sexo_animal": "Sexo: M",
      "altura_animal": "Altura: Aprox. 3 metros de altura",
      "tipo_animal": "Tipo Animal: Mamífero",
      "alimentacao_animal": "Carnívoro",
      "nome_cientifico_animal": 'Nome Cientifico: Ursus maritimus',
      'image_animal': 'lib/images/ursopolar.jpg',
      'image_primeira_animal': 'lib/images/ursopolarprimeiro.jpg',
      'image_segunda_animal': 'lib/images/ursopolarsegundo.jpg',
      'image_terceira_animal': 'lib/images/ursopolarterceiro.jpg',
    },
    //Inserindo o animal Urso polar
{
   "classificacao_animal":"Classificação: Aquatico",
   "nome_animal":"Tartaruga Marinha",
    "bioma_animal": "Bioma:Aquatico",
    "familia_cientifica_animal": " Familia.Cienti:Chelonidae",
    "populacao_animal": "População: Em cerca de 2.000",
    "peso_animal": 'Peso: Em cerca de 900kg',
    "sexo_animal":"macho/femea",
    "altura_animal": 'de 5,5cm á 2,1 metros de comprimento',
    "tipo_animal":'Anfibio',
    "alimentacao_animal":'Herbivoro',
     "nome_cientifico_animal":  'Nome. Cient:Chelonioidea',
     "image_animal" :'lib/images/tartaruga.png',
      "image_primeira_animal" : 'lib/images/tartarugasegunda.png',
     "image_segunda_animal" : 'lib/images/tartarugaprimeira.png',
       "image_terceira_animal" : 'lib/images/tartarugaterceira.png',
},
{
   "classificacao_animal":"Classificação: Terrestre",
   "nome_animal":"Orangotango",
    "bioma_animal": "Bioma:Floresta Tropicais",
    "familia_cientifica_animal": " Familia.Cienti:Hominidae",
    "populacao_animal":  'População: Em cerca de 100 mil',
    "peso_animal":  'Peso: Em cerca de 100kg',
    "sexo_animal":"macho/femea",
    "altura_animal": 'Tamanho: Pode atingir ate 1,8 metros',
    "tipo_animal":'Mamifero',
    "alimentacao_animal":'Herbivoro',
     "nome_cientifico_animal":  'Nome. Cient:Pongo',
     "image_animal" :'lib/images/orangotango.png',
      "image_primeira_animal" : 'lib/images/macacolaranja.jpg',
     "image_segunda_animal" : 'lib/images/macacolaranjasegundo.png',
       "image_terceira_animal" : 'lib/images/macacolaranjaterceiro.jpg',
},
  ]
};

/*class SobreAnimal {
  // observação essa lista abaixo tem o subtipo do construtor Animal por isso ele requer as variaveis que declaramos
  static List<Animal> tabela = [
    Animal(
        'Bioma: Savana',
        'População: 20.000',
        'Peso: 190kg',
        'Sexo: Macho ou femea',
        'Leão',
        'Altura: De 1,37 a 2m',
        'Tipo Animal: Mamifero',
        'Carnivoro',
        'lib/images/leao.jpg',
        'lib/images/leaoarvore.jpg',
        'lib/images/leaoarv.jpg',
        'lib/images/leaoalbino.jpg',
        'Fam. Cient.: Panthera leo',
        'Nome Cient: Felidae'),
// inserindo o animal Leão
    Animal(
        'Bioma: Semi-aquaticos',
        'População: Desconhecido',
        'Peso: De 36 a 66kg',
        "Sexo: Macho ou Femêa",
        'Capivara',
        'Altura: De 54 á  64cm',
        'Tipo Animal: Mamifero Roedor',
        'Herbivoro',
        'lib/images/capivara.png',
        'lib/images/capivaraprimeira.png',
        'lib/images/capivarasegundas.jpg',
        'lib/images/capivaraterceiras.jpg',
        'Fam. Cient: Hydrochoerus hydrochaeris',
        'Nome. Cient: Caviidae'),
// inserindo o animal capivara
    Animal(
        "Bioma: Savana",
        'População: Aprox. 1.830',
        'Peso: 160kg',
        'Sexo: Macho ou Femêa',
        'Dragão de Komodo',
        'Altura: 40cm de Altura',
        'Tipo Animal: Réptil',
        'Carnivoro',
        'lib/images/komodo.jpg',
        'lib/images/komodoprimeiro.jpg',
        'lib/images/komodosegundo.jpg',
        'lib/images/komodoterceiro.png',
        'Fam. Cient.: Varanus komodoensis',
        'Nome. Cient.:Varanus'),
// inserindo o animal Dragão de Komodo
    Animal(
        'Bioma: Florestas tropicais',
        'População: Aprox. 1.000',
        'Peso: 200kg',
        'Macho ou femêa',
        'Gorila',
        '1,60 de altura',
        'Mamífero',
        'Herbívoro',
        'lib/images/gorila.jpg',
        'lib/images/gorilaprimeiro.jpg',
        'lib/images/gorilasegundo.png',
        'lib/images/gorilaterceiros.jpg',
        'Familia. Cient:Gorila',
        'Nome. Cient:Hominidae'),
// inserindo o animal Gorila
    Animal(
        'Bioma: Temperado e tropical',
        'População: Aprox. 3.500',
        'Peso: De 520 a 1.100kg',
        'Macho/femea',
        'Tubarão Branco',
        'Tamanho: De 4 a 6m de comprimento',
        'Peixe',
        'Carnivoro',
        'lib/images/tubarao.jpg',
        'lib/images/tubaraofera.jpg',
        'lib/images/tubaraosalto.jpg',
        'lib/images/tub.jpg',
        'Familia. Cient:Lamnidae',
        'Nome. Cient:Carcharodon carcharias'),
// inserindo o animal Tubarão Branco
    Animal(
        'Bioma: Abiente Aquatico',
        'População: 200 mil de habitanyes',
        'Peso: 2,4kg',
        'Macho/Femêa',
        'Ornitorrinco',
        '50 centimetros',
        'Mamifero',
        'Carnivoro',
        'lib/images/ornitorrinco.png',
        'lib/images/ornitorrinco.jpg',
        'lib/images/orni.jpg',
        'lib/images/ornisegundo.jpg',
        'Familia. Cient:Ornithorhynchus anatinus',
        'Nome. Cient:Ornithorhynchidae'),
// inserindo o animal ornotorrinco//
    Animal(
        'Circulo Polar Artico',
        'em cerca de 25.000',
        '450kg',
        'Macho/Femêa',
        'Urso Polar',
        'Aproxi em 3 metros de altura',
        'Mamifero',
        'Carnivoro',
        'lib/images/ursopolar.jpg',
        'lib/images/ursopolarprimeiro.jpg',
        'lib/images/ursopolarsegundo.jpg',
        'lib/images/ursopolarterceiro.jpg',
        'Familia. Cient:Ursidae',
        'Nome. Cientifico:Ursus maritimus'),
// inserindo o urso polar
    Animal(
        'Bioma: Floresta Temperada e Taiga',
        'População: Em cerca de 10 mil',
        'Peso: Aproxi em 700kg',
        'Macho/Femêa',
        'Alce',
        'Tamanho: 2,1 metros de altura',
        'Mamifero',
        'Herbivoro',
        'lib/images/alce.png',
        'lib/images/alceprimeiro.jpg',
        'lib/images/alcesegundo.jpg',
        'lib/images/alceterceiro.jpg',
        'Familia. Cient:Cervídeos',
        'Nome. Cient:Alces alces'),
// inserindo o Alce
    Animal(
        'Floresta Tropicais',
        'População: Em cerca de 100 mil',
        'Peso: Em cerca de 100kg',
        'Macho/Femêa',
        'Orangotango',
        'Tamanho: Pode atingir ate 1,8 metros',
        'Mamifero',
        'Herbivoro',
        'lib/images/orangotango.png',
        'lib/images/macacolaranja.jpg',
        'lib/images/macacolaranjasegundo.png',
        'lib/images/macacolaranjaterceiro.jpg',
        'Familia. Cient:Hominidae',
        'Nome. Cient:Pongo'),
// inserindo o orangutango
    Animal(
        'Bioma aquatico',
        'População: 350 a 500 mil de habitantes',
        'Peso: Em cerca de 150kg',
        'Macho/Femêa',
        'Foca Cinzenta',
        'de 1,6 á 1,9 metros de comprimento',
        'Mamifero',
        'Carnivoro',
        'lib/images/foca.png',
        'lib/images/focaprimeira.jpg',
        'lib/images/focasegunda.jpg',
        'lib/images/focaterceira.jpg',
        'Fam. Cient.:Phocidae',
        'Nome. Cient:Halichoerus grypus'),
// inserindo a foca cinzenta
    Animal(
        'Bioma desertico',
        'População: Em volta de 1,4 milhões',
        'Peso: Em cerca de 650kg',
        'Macho/Femêa',
        'Camelo',
        'De 1,8 á 2 metros de Altura',
        'Mamifero',
        'Herbivoro',
        'lib/images/camelo.png',
        'lib/images/cameloprimeiro.jpg',
        'lib/images/camelosegundo.jpg',
        'lib/images/cameloterceiro.jpg',
        'Fam. Cient:Camelidae',
        'Nome. Cient:Camelus'),
// inserindo o animal camelo
    Animal(
        'Savanas',
        'População: Em vola de 117 mil',
        'Peso:  Em volta de 1,9 toneladas',
        'Macho/Femêa',
        'Girafa',
        'Tamanho: 5,7 metros',
        'Mamifero',
        'Herbivoro',
        'lib/images/girafa.png',
        'lib/images/gira.jpg',
        'lib/images/gir.jpg',
        'lib/images/girafaterceira.jpg',
        'Familia. Cient:Giraffidae',
        'Nome. Cient:Giraffa'),
         Animal(
        'Bioma Desertico',
        'População: 1.600 especies',
        'peso:Desconhecido',
        'macho/femea',
        'Escorpião',
        'comprimento:12 á 25cm',
        'Artropoda',
        'Carnivoro',
        'lib/images/escorpiaoprimeiro.png',
        'lib/images/escorpiaosegundo.png',
        'lib/images/escorpiaoterceiro.png',
        'lib/images/escorpiaoquarto.png',
        'Familia. Cient:Buthidae',
        'Nome. Cient:Scorpiones'),
         Animal(
        'Bioma aquatico',
        'População:em cerca de 30 especies',
        'Peso: Em cerca de 900kg',
        'Macho/Femêa',
        'Tartaruga Marinha',
        'de 5,5cm á 2,1 metros de comprimento',
        'Anfibio',
        'Herbivoro',
        'lib/images/tartaruga.png',
        'lib/images/tartarugasegunda.png',
        'lib/images/tartarugaprimeira.png',
        'lib/images/tartarugaterceira.png',
        'Fam. Cient.:Cheloniidae',
        'Nome. Cient:Chelonioidea'),
// inserindo o animal girafa
  ];
  static List<Animal> animaisAquaticos = [
    Animal(
        'Bioma: Ambiente Aquatico',
        'População: 200 mil de habitanyes',
        'Peso: 2,4kg',
        'Macho/Femêa',
        'Ornitorrinco',
        '50 centimetros',
        'Mamifero',
        'Carnivoro',
        'lib/images/ornitorrinco.png',
        'lib/images/ornitorrinco.jpg',
        'lib/images/orni.jpg',
        'lib/images/ornisegundo.jpg',
        'Familia. Cient:Ornithorhynchus anatinus',
        'Nome. Cient:Ornithorhynchidae'),
    Animal(
        'Bioma aquatico',
        'População: 350 a 500 mil de habitantes',
        'Peso: Em cerca de 150kg',
        'Macho/Femêa',
        'Foca Cinzenta',
        'de 1,6 á 1,9 metros de comprimento',
        'Mamifero',
        'Carnivoro',
        'lib/images/foca.png',
        'lib/images/focaprimeira.jpg',
        'lib/images/focasegunda.jpg',
        'lib/images/focaterceira.jpg',
        'Fam. Cient.:Phocidae',
        'Nome. Cient:Halichoerus grypus'),
    Animal(
        'Bioma aquatico',
        'População:em cerca de 30 especies',
        'Peso: Em cerca de 900kg',
        'Macho/Femêa',
        'Tartaruga Marinha',
        'de 5,5cm á 2,1 metros de comprimento',
        'Anfibio',
        'Herbivoro',
        'lib/images/tartaruga.png',
        'lib/images/tartarugasegunda.png',
        'lib/images/tartarugaprimeira.png',
        'lib/images/tartarugaterceira.png',
        'Fam. Cient.:Cheloniidae',
        'Nome. Cient:Chelonioidea'),
  ];
  static List<Animal> animaisTerrestres = [
    Animal(
        'Bioma desertico',
        'População: Em volta de 1,4 milhões',
        'Peso: Em cerca de 650kg',
        'Macho/Femêa',
        'Camelo',
        'De 1,8 á 2 metros de Altura',
        'Mamifero',
        'Herbivoro',
        'lib/images/camelo.png',
        'lib/images/cameloprimeiro.jpg',
        'lib/images/camelosegundo.jpg',
        'lib/images/cameloterceiro.jpg',
        'Fam. Cient:Camelidae',
        'Nome. Cient:Camelus'),
    Animal(
        'Savanas',
        'População: Em vola de 117 mil',
        'Peso:  Em volta de 1,9 toneladas',
        'Macho/Femêa',
        'Girafa',
        'Tamanho: 5,7 metros',
        'Mamifero',
        'Herbivoro',
        'lib/images/girafa.png',
        'lib/images/gira.jpg',
        'lib/images/gir.jpg',
        'lib/images/girafaterceira.jpg',
        'Familia. Cient:Giraffidae',
        'Nome. Cient:Giraffa'),
    Animal(
        'Floresta Tropicais',
        'População: Em cerca de 100 mil',
        'Peso: Em cerca de 100kg',
        'Macho/Femêa',
        'Orangotango',
        'Tamanho: Pode atingir ate 1,8 metros',
        'Mamifero',
        'Herbivoro',
        'lib/images/orangotango.png',
        'lib/images/macacolaranja.jpg',
        'lib/images/macacolaranjasegundo.png',
        'lib/images/macacolaranjaterceiro.jpg',
        'Familia. Cient:Hominidae',
        'Nome. Cient:Pongo'),
  ];
  static List<Animal> animaisAves = [
    Animal(
        'Bioma: Savana',
        'População: 20.000',
        'Peso: 190kg',
        'Sexo: Macho ou femea',
        'Leão',
        'Altura: De 1,37 a 2m',
        'Tipo Animal: Mamifero',
        'Carnivoro',
        'lib/images/leao.jpg',
        'lib/images/leaoarvore.jpg',
        'lib/images/leaoarv.jpg',
        'lib/images/leaoalbino.jpg',
        'Fam. Cient.: Panthera leo',
        'Nome Cient: Felidae'),
    Animal(
        'Bioma: Temperado e tropical',
        'População: Aprox. 3.500',
        'Peso: De 520 a 1.100kg',
        'Macho/femea',
        'Tubarão Branco',
        'Tamanho: De 4 a 6m de comprimento',
        'Peixe',
        'Carnivoro',
        'lib/images/tubarao.jpg',
        'lib/images/tubaraofera.jpg',
        'lib/images/tubaraosalto.jpg',
        'lib/images/tub.jpg',
        'Familia. Cient:Lamnidae',
        'Nome. Cient:Carcharodon carcharias'),
  ];
  static List<Animal> animaisPeconhentos = [
    Animal(
        "Bioma: Savana",
        'População: Aprox. 1.830',
        'Peso: 160kg',
        'Sexo: Macho ou Femêa',
        'Dragão de Komodo',
        'Altura: 40cm de Altura',
        'Tipo Animal: Réptil',
        'Carnivoro',
        'lib/images/komodo.jpg',
        'lib/images/komodoprimeiro.jpg',
        'lib/images/komodosegundo.jpg',
        'lib/images/komodoterceiro.png',
        'Fam. Cient.: Varanus komodoensis',
        'Nome. Cient.:Varanus'),
    Animal(
        'Bioma: Florestas tropicais',
        'População: Aprox. 1.000',
        'Peso: 200kg',
        'Macho ou femêa',
        'Gorila',
        '1,60 de altura',
        'Mamífero',
        'Herbívoro',
        'lib/images/gorila.jpg',
        'lib/images/gorilaprimeiro.jpg',
        'lib/images/gorilasegundo.png',
        'lib/images/gorilaterceiros.jpg',
        'Familia. Cient:Gorila',
        'Nome. Cient:Hominidae'),
    Animal(
        'Bioma Desertico',
        'População:1600 especies',
        'peso:Desconhecido',
        'macho/femea',
        'Escorpião',
        'comprimento:12 á 25cm',
        'Artropoda',
        'Carnivoro',
        'lib/images/escorpiaoprimeiro.png',
        'lib/images/escorpiaosegundo.png',
        'lib/images/escorpiaoterceiro.png',
        'lib/images/escorpiaoquarto.png',
        'Familia. Cient:Buthidae',
        'Nome. Cient:Scorpiones')
  ];
}*/
